server:
  port: 8083
  forward-headers-strategy: framework

spring:
  datasource:
    url: jdbc:h2:mem:administracionesdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update

springdoc:
  api-docs:
    path: /v3/api-docs

eureka:
  client:
    service-url:
      defaultZone: http://eurekaserver:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
